--role table in jwtSec already exists. if enable comments it will overwrite these 2 columns and gives error on each run of the programm.
--INSERT  INTO role(name) VALUES('ROLE_USER');
--INSERT  INTO role(name) VALUES('ROLE_ADMIN');
